// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "0f95eeb5-b7e7-4acb-8635-8f3b3cfa6d04";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onAllChange();
void onSpeedChange();
void onBackwardChange();
void onForwardChange();
void off();

int all;
int speed;
bool backward;
bool forward;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(all, READWRITE, ON_CHANGE, onAllChange, 255);
  ArduinoCloud.addProperty(speed, READWRITE, ON_CHANGE, onSpeedChange, 5);
  ArduinoCloud.addProperty(backward, READWRITE, ON_CHANGE, onBackwardChange);
  ArduinoCloud.addProperty(forward, READWRITE, ON_CHANGE, onForwardChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
